### ISSUE TITLE
Crash Removing Redirects

### ISSUE THREAD

**Issue by Annarkwin** [sethstenzel/tiny-redirect#1]
After fresh installation, I was successful in accessing the web interface, but immediately upon removing each default redirect, the app crashed and was no longer accessible. I had to drop the original db copy back in place for it to start working again.

**Comment by sethstenzel** [comment]
The issue has been resolved; If all redirects are deleted, one example redirect will be created automatically. Additionally if the database is deleted, it will be recreated, and if it is corrupted, the app will crash and warn to delete.
